fix formatting

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -59,24 +59,24 @@ jobs:
       uses: browser-actions/setup-chrome@v1
 
     - name: Package Chrome App into .crx
-          id: crx_package
-          run: |
-            echo "${{ secrets.IWA_KEY }}" > key.pem
-            # Note: Chrome's pack-extension outputs the .crx file one level above the source directory
-            google-chrome --pack-extension=examples/chrome-app-example/dist --pack-extension-key=key.pem
-            CRX_PATH="examples/chrome-app-example/chrome-app.crx"
-            if [ -f "$CRX_PATH" ]; then
-              mv "$CRX_PATH" "chrome-app-${{ steps.app_version.outputs.version }}.crx"
-              echo "crx_name=chrome-app-${{ steps.app_version.outputs.version }}.crx" >> $GITHUB_OUTPUT
-            else
-              echo "CRX file not found at $CRX_PATH"
-              exit 1
-            fi
+      id: crx_package
+      run: |
+        echo "${{ secrets.IWA_KEY }}" > key.pem
+        # Note: Chrome's pack-extension outputs the .crx file one level above the source directory
+        google-chrome --pack-extension=examples/chrome-app-example/dist --pack-extension-key=key.pem
+        CRX_PATH="examples/chrome-app-example/chrome-app.crx"
+        if [ -f "$CRX_PATH" ]; then
+          mv "$CRX_PATH" "chrome-app-${{ steps.app_version.outputs.version }}.crx"
+          echo "crx_name=chrome-app-${{ steps.app_version.outputs.version }}.crx" >> $GITHUB_OUTPUT
+        else
+          echo "CRX file not found at $CRX_PATH"
+          exit 1
+        fi
 
     - name: Upload Chrome App .crx Artifact
-          uses: actions/upload-artifact@v4
-          with:
-            name: chrome-app-build-${{ steps.app_version.outputs.version }}
-            path: ${{ steps.crx_package.outputs.crx_name }}
-            retention-days: 7
-            overwrite: true
+      uses: actions/upload-artifact@v4
+      with:
+        name: chrome-app-build-${{ steps.app_version.outputs.version }}
+        path: ${{ steps.crx_package.outputs.crx_name }}
+        retention-days: 7
+        overwrite: true
